### ISSUE TITLE
bibtex issuses

### ISSUE THREAD

**Issue by laszewsk** [bigdata-i523/hid224#1]
Database file #1: report.bib
- [ ] Warning--empty year in bigdatapredictive02
- [ ] Warning--empty year in bigdatarevenue09
- [ ] Warning--no number and no volume in jianfangwang07
- [ ] Warning--page numbers missing in both pages and numpages fields in jianfangwang07
- [ ] Warning--page numbers missing in both pages and numpages fields in kahnliu10
- [ ] Warning--page numbers missing in both pages and numpages fields in kortefrolick03
- [ ] Warning--no number and no volume in kasr11
- [ ] Warning--page numbers missing in both pages and numpages fields in kasr11
- [ ] Warning--page numbers missing in both pages and numpages fields in phillipswrenhoskisson01

**Comment by Neha41093** [comment]
Corrected.
